export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const NAME_OF_PAGE = 'NAME_OF_PAGE';

export const SET_PHOTO = 'SET_PHOTO';
export const GET_ALL_PHOTOS = 'GET_ALL_PHOTOS';
export const GET_ONE_PHOTO = 'GET_ONE_PHOTO';
export const DELETE_PHOTO = 'DELETE_PHOTO';

export const SET_IMAGE_GROUP = 'SET_IMAGE_GROUP';
export const UPDATE_IMAGE_GROUP = 'UPDATE_IMAGE_GROUP';
export const GET_ALL_IMAGE_GROUPS = 'GET_ALL_IMAGE_GROUPS';
export const GET_ONE_IMAGE_GROUP = 'GET_ONE_IMAGE_GROUP';
export const DELETE_IMAGE_GROUP = 'DELETE_IMAGE_GROUP';
