export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const NAME_OF_PAGE = 'NAME_OF_PAGE';

export const SET_PHOTO = 'SET_PHOTO';
export const UPDATE_PHOTO = 'UPDATE_PHOTO';
export const GET_ALL_PHOTOS = 'GET_ALL_PHOTOS';
export const GET_ONE_PHOTO = 'GET_ONE_PHOTO';
export const DELETE_PHOTO = 'DELETE_PHOTO';

export const SET_IMAGE_GROUP = 'SET_IMAGE_GROUP';
export const UPDATE_IMAGE_GROUP = 'UPDATE_IMAGE_GROUP';
export const GET_ALL_IMAGE_GROUPS = 'GET_ALL_IMAGE_GROUPS';
export const GET_ONE_IMAGE_GROUP = 'GET_ONE_IMAGE_GROUP';
export const DELETE_IMAGE_GROUP = 'DELETE_IMAGE_GROUP';

export const SET_USER = 'SET_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_ONE_USER = 'GET_ONE_USER';
export const DELETE_USER = 'DELETE_USER';

export const SET_CLIENT_REQUEST = 'SET_CLIENT_REQUEST';
export const UPDATE_CLIENT_REQUEST = 'UPDATE_CLIENT_REQUEST';
export const GET_ALL_CLIENT_REQUESTS = 'GET_ALL_CLIENT_REQUESTS';
export const GET_ONE_CLIENT_REQUEST = 'GET_ONE_CLIENT_REQUEST';
export const DELETE_CLIENT_REQUEST = 'DELETE_CLIENT_REQUEST';

export const SET_CATEGORY_OF_CLIENT = 'SET_CATEGORY_OF_CLIENT';
export const UPDATE_CATEGORY_OF_CLIENT = 'UPDATE_CATEGORY_OF_CLIENT';
export const GET_ALL_CATEGORY_OF_CLIENTS = 'GET_ALL_CATEGORY_OF_CLIENTS';
export const GET_ONE_CATEGORY_OF_CLIENT = 'GET_ONE_CATEGORY_OF_CLIENT';
export const DELETE_CATEGORY_OF_CLIENT = 'DELETE_CATEGORY_OF_CLIENT';

export const SET_ENTERED_CERTIFICATE_OF_COMPLETION =
  'SET_ENTERED_CERTIFICATE_OF_COMPLETION';
export const UPDATE_ENTERED_CERTIFICATE_OF_COMPLETION =
  'UPDATE_ENTERED_CERTIFICATE_OF_COMPLETION';
export const GET_ALL_ENTERED_CERTIFICATE_OF_COMPLETIONS =
  'GET_ALL_ENTERED_CERTIFICATE_OF_COMPLETIONS';
export const GET_ONE_ENTERED_CERTIFICATE_OF_COMPLETION =
  'GET_ONE_ENTERED_CERTIFICATE_OF_COMPLETION';
export const DELETE_ENTERED_CERTIFICATE_OF_COMPLETION =
  'DELETE_ENTERED_CERTIFICATE_OF_COMPLETION';

export const SET_ENTERED_INVOICE_MIXED = 'SET_ENTERED_INVOICE_MIXED';
export const UPDATE_ENTERED_INVOICE_MIXED = 'UPDATE_ENTERED_INVOICE_MIXED';
export const GET_ALL_ENTERED_INVOICE_MIXEDS = 'GET_ALL_ENTERED_INVOICE_MIXEDS';
export const GET_ONE_ENTERED_INVOICE_MIXED = 'GET_ONE_ENTERED_INVOICE_MIXED';
export const DELETE_ENTERED_INVOICE_MIXED = 'DELETE_ENTERED_INVOICE_MIXED';

export const SET_ENTERED_INVOICE_PRODUCT = 'SET_ENTERED_INVOICE_PRODUCT';
export const UPDATE_ENTERED_INVOICE_PRODUCT = 'UPDATE_ENTERED_INVOICE_PRODUCT';
export const GET_ALL_ENTERED_INVOICE_PRODUCTS =
  'GET_ALL_ENTERED_INVOICE_PRODUCTS';
export const GET_ONE_ENTERED_INVOICE_PRODUCT =
  'GET_ONE_ENTERED_INVOICE_PRODUCT';
export const DELETE_ENTERED_INVOICE_PRODUCT = 'DELETE_ENTERED_INVOICE_PRODUCT';

export const SET_ENTERED_INVOICE_SERVICE_JOB =
  'SET_ENTERED_INVOICE_SERVICE_JOB';
export const UPDATE_ENTERED_INVOICE_SERVICE_JOB =
  'UPDATE_ENTERED_INVOICE_SERVICE_JOB';
export const GET_ALL_ENTERED_INVOICE_SERVICE_JOBS =
  'GET_ALL_ENTERED_INVOICE_SERVICE_JOBS';
export const GET_ONE_ENTERED_INVOICE_SERVICE_JOB =
  'GET_ONE_ENTERED_INVOICE_SERVICE_JOB';
export const DELETE_ENTERED_INVOICE_SERVICE_JOB =
  'DELETE_ENTERED_INVOICE_SERVICE_JOB';

export const SET_ENTERED_SALES_INVOICE_NAKLADNAYA =
  'SET_ENTERED_SALES_INVOICE_NAKLADNAYA';
export const UPDATE_ENTERED_SALES_INVOICE_NAKLADNAYA =
  'UPDATE_ENTERED_SALES_INVOICE_NAKLADNAYA';
export const GET_ALL_ENTERED_SALES_INVOICE_NAKLADNAYAS =
  'GET_ALL_ENTERED_SALES_INVOICE_NAKLADNAYAS';
export const GET_ONE_ENTERED_SALES_INVOICE_NAKLADNAYA =
  'GET_ONE_ENTERED_SALES_INVOICE_NAKLADNAYA';
export const DELETE_ENTERED_SALES_INVOICE_NAKLADNAYA =
  'DELETE_ENTERED_SALES_INVOICE_NAKLADNAYA';

export const SET_OUR_BANK_INCOME = 'SET_OUR_BANK_INCOME';
export const UPDATE_OUR_BANK_INCOME = 'UPDATE_OUR_BANK_INCOME';
export const GET_ALL_OUR_BANK_INCOMES = 'GET_ALL_OUR_BANK_INCOMES';
export const GET_ONE_OUR_BANK_INCOME = 'GET_ONE_OUR_BANK_INCOME';
export const DELETE_OUR_BANK_INCOME = 'DELETE_OUR_BANK_INCOME';

export const SET_OUR_CERTIFICATE_OF_COMPLETION =
  'SET_OUR_CERTIFICATE_OF_COMPLETION';
export const UPDATE_OUR_CERTIFICATE_OF_COMPLETION =
  'UPDATE_OUR_CERTIFICATE_OF_COMPLETION';
export const GET_ALL_OUR_CERTIFICATE_OF_COMPLETIONS =
  'GET_ALL_OUR_CERTIFICATE_OF_COMPLETIONS';
export const GET_ONE_OUR_CERTIFICATE_OF_COMPLETION =
  'GET_ONE_OUR_CERTIFICATE_OF_COMPLETION';
export const DELETE_OUR_CERTIFICATE_OF_COMPLETION =
  'DELETE_OUR_CERTIFICATE_OF_COMPLETION';

export const SET_OUR_INVOICE_MIXED = 'SET_OUR_INVOICE_MIXED';
export const UPDATE_OUR_INVOICE_MIXED = 'UPDATE_OUR_INVOICE_MIXED';
export const GET_ALL_OUR_INVOICE_MIXEDS = 'GET_ALL_OUR_INVOICE_MIXEDS';
export const GET_ONE_OUR_INVOICE_MIXED = 'GET_ONE_OUR_INVOICE_MIXED';
export const DELETE_OUR_INVOICE_MIXED = 'DELETE_OUR_INVOICE_MIXED';

export const SET_OUR_INVOICE_PRODUCT = 'SET_OUR_INVOICE_PRODUCT';
export const UPDATE_OUR_INVOICE_PRODUCT = 'UPDATE_OUR_INVOICE_PRODUCT';
export const GET_ALL_OUR_INVOICE_PRODUCTS = 'GET_ALL_OUR_INVOICE_PRODUCTS';
export const GET_ONE_OUR_INVOICE_PRODUCT = 'GET_ONE_OUR_INVOICE_PRODUCT';
export const DELETE_OUR_INVOICE_PRODUCT = 'DELETE_OUR_INVOICE_PRODUCT';

export const SET_OUR_INVOICE_SERVICE_JOB = 'SET_OUR_INVOICE_SERVICE_JOB';
export const UPDATE_OUR_INVOICE_SERVICE_JOB = 'UPDATE_OUR_INVOICE_SERVICE_JOB';
export const GET_ALL_OUR_INVOICE_SERVICE_JOBS =
  'GET_ALL_OUR_INVOICE_SERVICE_JOBS';
export const GET_ONE_OUR_INVOICE_SERVICE_JOB =
  'GET_ONE_OUR_INVOICE_SERVICE_JOB';
export const DELETE_OUR_INVOICE_SERVICE_JOB = 'DELETE_OUR_INVOICE_SERVICE_JOB';

export const SET_OUR_PAYMENT = 'SET_OUR_PAYMENT';
export const UPDATE_OUR_PAYMENT = 'UPDATE_OUR_PAYMENT';
export const GET_ALL_OUR_PAYMENTS = 'GET_ALL_OUR_PAYMENTS';
export const GET_ONE_OUR_PAYMENT = 'GET_ONE_OUR_PAYMENT';
export const DELETE_OUR_PAYMENT = 'DELETE_OUR_PAYMENT';

export const SET_OUR_SALES_INVOICE_NAKLADNAYA =
  'SET_OUR_SALES_INVOICE_NAKLADNAYA';
export const UPDATE_OUR_SALES_INVOICE_NAKLADNAYA =
  'UPDATE_OUR_SALES_INVOICE_NAKLADNAYA';
export const GET_ALL_OUR_SALES_INVOICE_NAKLADNAYAS =
  'GET_ALL_OUR_SALES_INVOICE_NAKLADNAYAS';
export const GET_ONE_OUR_SALES_INVOICE_NAKLADNAYA =
  'GET_ONE_OUR_SALES_INVOICE_NAKLADNAYA';
export const DELETE_OUR_SALES_INVOICE_NAKLADNAYA =
  'DELETE_OUR_SALES_INVOICE_NAKLADNAYA';

/////////////////////////////////////////////////////////////////////////////////////

export const SET_BANK_NAME = 'SET_BANK_NAME';
export const UPDATE_BANK_NAME = 'UPDATE_BANK_NAME';
export const GET_ALL_BANK_NAMES = 'GET_ALL_BANK_NAMES';
export const GET_ONE_BANK_NAME = 'GET_ONE_BANK_NAME';
export const DELETE_BANK_NAME = 'DELETE_BANK_NAME';

export const SET_CLIENT = 'SET_CLIENT';
export const UPDATE_CLIENT = 'UPDATE_CLIENT';
export const GET_ALL_CLIENTS = 'GET_ALL_CLIENTS';
export const GET_ONE_CLIENT = 'GET_ONE_CLIENT';
export const DELETE_CLIENT = 'DELETE_CLIENT';

export const SET_FIRST_PERSON_POSITION = 'SET_FIRST_PERSON_POSITION';
export const UPDATE_FIRST_PERSON_POSITION = 'UPDATE_FIRST_PERSON_POSITION';
export const GET_ALL_FIRST_PERSON_POSITIONS = 'GET_ALL_FIRST_PERSON_POSITIONS';
export const GET_ONE_FIRST_PERSON_POSITION = 'GET_ONE_FIRST_PERSON_POSITION';
export const DELETE_FIRST_PERSON_POSITION = 'DELETE_FIRST_PERSON_POSITION';

export const SET_GROUP_OF_PRODUCT = 'SET_GROUP_OF_PRODUCT';
export const UPDATE_GROUP_OF_PRODUCT = 'UPDATE_GROUP_OF_PRODUCT';
export const GET_ALL_GROUP_OF_PRODUCTS = 'GET_ALL_GROUP_OF_PRODUCTS';
export const GET_ONE_GROUP_OF_PRODUCT = 'GET_ONE_GROUP_OF_PRODUCT';
export const DELETE_GROUP_OF_PRODUCT = 'DELETE_GROUP_OF_PRODUCT';

export const SET_GROUP_OF_SERVICE_JOB = 'SET_GROUP_OF_SERVICE_JOB';
export const UPDATE_GROUP_OF_SERVICE_JOB = 'UPDATE_GROUP_OF_SERVICE_JOB';
export const GET_ALL_GROUP_OF_SERVICE_JOBS = 'GET_ALL_GROUP_OF_SERVICE_JOBS';
export const GET_ONE_GROUP_OF_SERVICE_JOB = 'GET_ONE_GROUP_OF_SERVICE_JOB';
export const DELETE_GROUP_OF_SERVICE_JOB = 'DELETE_GROUP_OF_SERVICE_JOB';

export const SET_OUR_FIRM = 'SET_OUR_FIRM';
export const UPDATE_OUR_FIRM = 'UPDATE_OUR_FIRM';
export const GET_ALL_OUR_FIRMS = 'GET_ALL_OUR_FIRMS';
export const GET_ONE_OUR_FIRM = 'GET_ONE_OUR_FIRM';
export const DELETE_OUR_FIRM = 'DELETE_OUR_FIRM';

export const SET_PHONE_OPERATOR = 'SET_PHONE_OPERATOR';
export const UPDATE_PHONE_OPERATOR = 'UPDATE_PHONE_OPERATOR';
export const GET_ALL_PHONE_OPERATORS = 'GET_ALL_PHONE_OPERATORS';
export const GET_ONE_PHONE_OPERATOR = 'GET_ONE_PHONE_OPERATOR';
export const DELETE_PHONE_OPERATOR = 'DELETE_PHONE_OPERATOR';

export const SET_PRODUCT = 'SET_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_ONE_PRODUCT = 'GET_ONE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

export const SET_SERVICE_JOB = 'SET_SERVICE_JOB';
export const UPDATE_SERVICE_JOB = 'UPDATE_SERVICE_JOB';
export const GET_ALL_SERVICE_JOBS = 'GET_ALL_SERVICE_JOBS';
export const GET_ONE_SERVICE_JOB = 'GET_ONE_SERVICE_JOB';
export const DELETE_SERVICE_JOB = 'DELETE_SERVICE_JOB';

export const SET_SUPPLIER = 'SET_SUPPLIER';
export const UPDATE_SUPPLIER = 'UPDATE_SUPPLIER';
export const GET_ALL_SUPPLIERS = 'GET_ALL_SUPPLIERS';
export const GET_ONE_SUPPLIER = 'GET_ONE_SUPPLIER';
export const DELETE_SUPPLIER = 'DELETE_SUPPLIER';

export const SET_TYPE_OF_ACTS_ON_BASIS_OF = 'SET_TYPE_OF_ACTS_ON_BASIS_OF';
export const UPDATE_TYPE_OF_ACTS_ON_BASIS_OF =
  'UPDATE_TYPE_OF_ACTS_ON_BASIS_OF';
export const GET_ALL_TYPE_OF_ACTS_ON_BASIS_OFS =
  'GET_ALL_TYPE_OF_ACTS_ON_BASIS_OFS';
export const GET_ONE_TYPE_OF_ACTS_ON_BASIS_OF =
  'GET_ONE_TYPE_OF_ACTS_ON_BASIS_OF';
export const DELETE_TYPE_OF_ACTS_ON_BASIS_OF =
  'DELETE_TYPE_OF_ACTS_ON_BASIS_OF';

export const SET_TYPE_OF_FIRM = 'SET_TYPE_OF_FIRM';
export const UPDATE_TYPE_OF_FIRM = 'UPDATE_TYPE_OF_FIRM';
export const GET_ALL_TYPE_OF_FIRMS = 'GET_ALL_TYPE_OF_FIRMS';
export const GET_ONE_TYPE_OF_FIRM = 'GET_ONE_TYPE_OF_FIRM';
export const DELETE_TYPE_OF_FIRM = 'DELETE_TYPE_OF_FIRM';

export const SET_TYPE_OF_SETTLEMENT = 'SET_TYPE_OF_SETTLEMENT';
export const UPDATE_TYPE_OF_SETTLEMENT = 'UPDATE_TYPE_OF_SETTLEMENT';
export const GET_ALL_TYPE_OF_SETTLEMENTS = 'GET_ALL_TYPE_OF_SETTLEMENTS';
export const GET_ONE_TYPE_OF_SETTLEMENT = 'GET_ONE_TYPE_OF_SETTLEMENT';
export const DELETE_TYPE_OF_SETTLEMENT = 'DELETE_TYPE_OF_SETTLEMENT';

export const SET_TYPE_OF_STREET = 'SET_TYPE_OF_STREET';
export const UPDATE_TYPE_OF_STREET = 'UPDATE_TYPE_OF_STREET';
export const GET_ALL_TYPE_OF_STREETS = 'GET_ALL_TYPE_OF_STREETS';
export const GET_ONE_TYPE_OF_STREET = 'GET_ONE_TYPE_OF_STREET';
export const DELETE_TYPE_OF_STREET = 'DELETE_TYPE_OF_STREET';

export const SET_TYPE_OF_TAX_PAYER_ON = 'SET_TYPE_OF_TAX_PAYER_ON';
export const UPDATE_TYPE_OF_TAX_PAYER_ON = 'UPDATE_TYPE_OF_TAX_PAYER_ON';
export const GET_ALL_TYPE_OF_TAX_PAYER_ONS = 'GET_ALL_TYPE_OF_TAX_PAYER_ONS';
export const GET_ONE_TYPE_OF_TAX_PAYER_ON = 'GET_ONE_TYPE_OF_TAX_PAYER_ON';
export const DELETE_TYPE_OF_TAX_PAYER_ON = 'DELETE_TYPE_OF_TAX_PAYER_ON';

export const SET_TYPE_OF_UNIT = 'SET_TYPE_OF_UNIT';
export const UPDATE_TYPE_OF_UNIT = 'UPDATE_TYPE_OF_UNIT';
export const GET_ALL_TYPE_OF_UNITS = 'GET_ALL_TYPE_OF_UNITS';
export const GET_ONE_TYPE_OF_UNIT = 'GET_ONE_TYPE_OF_UNIT';
export const DELETE_TYPE_OF_UNIT = 'DELETE_TYPE_OF_UNIT';

export const SET_UNIT = 'SET_UNIT';
export const UPDATE_UNIT = 'UPDATE_UNIT';
export const GET_ALL_UNITS = 'GET_ALL_UNITS';
export const GET_ONE_UNIT = 'GET_ONE_UNIT';
export const DELETE_UNIT = 'DELETE_UNIT';

export const SET_WORKER = 'SET_WORKER';
export const UPDATE_WORKER = 'UPDATE_WORKER';
export const GET_ALL_WORKERS = 'GET_ALL_WORKERS';
export const GET_ONE_WORKER = 'GET_ONE_WORKER';
export const DELETE_WORKER = 'DELETE_WORKER';

export const SET_CITY = 'SET_CITY';
export const UPDATE_CITY = 'UPDATE_CITY';
export const GET_ALL_CITYS = 'GET_ALL_CITYS';
export const GET_ONE_CITY = 'GET_ONE_CITY';
export const DELETE_CITY = 'DELETE_CITY';

export const SET_STREET = 'SET_STREET';
export const UPDATE_STREET = 'UPDATE_STREET';
export const GET_ALL_STREETS = 'GET_ALL_STREETS';
export const GET_ONE_STREET = 'GET_ONE_STREET';
export const DELETE_STREET = 'DELETE_STREET';
